import { EducationalContent, InspirationContent } from '../../shared/types/index.js';

export interface ContentFiles {
  tips: { tips: string[] };
  facts: { facts: string[] };
  inspiration: { quotes: string[]; jokes: string[] };
}

export class ContentManager {
  private static instance: ContentManager;
  private contentCache: {
    tips: string[];
    facts: string[];
    quotes: string[];
    jokes: string[];
  } | null = null;
  private lastLoadDate: string | null = null;

  private constructor() {}

  public static getInstance(): ContentManager {
    if (!ContentManager.instance) {
      ContentManager.instance = new ContentManager();
    }
    return ContentManager.instance;
  }

  /**
   * Load content from embedded data (since fs is not available in serverless environment)
   */
  private loadContentFromFiles(): ContentFiles {
    try {
      // Import content directly since we can't use fs in serverless environment
      const tips = this.getEmbeddedTips();
      const facts = this.getEmbeddedFacts();
      const inspiration = this.getEmbeddedInspiration();

      // Validate content structure
      this.validateContentStructure(tips, facts, inspiration);

      return { tips, facts, inspiration };
    } catch (error) {
      console.error('Error loading content:', error);
      return this.getFallbackContent();
    }
  }

  /**
   * Get educational tips from embedded data
   */
  private getEmbeddedTips(): { tips: string[] } {
    return {
      tips: [
        "Check the hands and feet: AI models often struggle with generating realistic hands and feet, so look for inconsistencies like extra fingers, distorted limbs, or unnatural poses.",
        "Look for strange patterns in textures: Repetitive or unnatural-looking textures in clothing, skin, or backgrounds can be a tell-tale sign of AI generation.",
        "Examine the eyes: In AI-generated portraits, the eyes may lack the depth and detail of a real photograph. Look for inconsistent reflections or pupils that are perfectly round.",
        "Analyze the lighting and shadows: AI-generated images may have inconsistent lighting, with shadows that don't match the direction of the light source.",
        "Scrutinize the background: Look for objects that are distorted, out of place, or blend into each other in a strange way.",
        "Check for perfect symmetry: Real-world objects and faces are rarely perfectly symmetrical. If an image looks too perfect, it may be AI-generated.",
        "Inspect the text: AI often struggles to generate readable and coherent text. Look for nonsensical words or characters.",
        "Look for a waxy or airbrushed appearance: AI-generated images can sometimes have an overly smooth or plastic-like texture, especially on skin.",
        "Examine the details: Zoom in on the image and look for small details that don't make sense, like misplaced buttons or jewelry that seems to merge with the skin.",
        "Trust your gut: If something feels 'off' or unsettling about an image, it could be a sign that it was generated by AI.",
        "Look for morphed objects: In some AI images, you might see objects that seem to morph into one another in an unnatural way.",
        "Check for repeating elements: AI can sometimes get stuck in a loop and repeat certain elements in the background or in a pattern.",
        "Examine hair and fur: Individual strands of hair or fur may look unrealistic or lack the natural variation of a real photo.",
        "Look for a lack of context: AI-generated images sometimes lack a clear story or context, with objects and people placed in a way that doesn't make sense.",
        "Check for emotional disconnect: While AI is getting better at generating realistic faces, the emotions expressed may not always match the context of the image.",
        "Look for an 'uncanny valley' effect: This is the feeling you get when something looks almost human, but not quite right.",
        "Examine the composition: AI-generated images can sometimes have a strange or unconventional composition that a human photographer would be unlikely to use.",
        "Look for a lack of physics: Objects in an AI-generated image may seem to defy gravity or interact with each other in a way that isn't physically possible.",
        "Check for a 'digital' look: Some AI images have a certain 'digital' quality to them, with colors that are too saturated or a lack of natural grain.",
        "Look for a lack of imperfections: Real photos often have imperfections like lens flare, dust spots, or motion blur. AI images are often too clean."
      ]
    };
  }

  /**
   * Get AI facts from embedded data
   */
  private getEmbeddedFacts(): { facts: string[] } {
    return {
      facts: [
        "That AI-generated image of the Pope in a puffy jacket? It fooled millions, including news outlets.",
        "The 'uncanny valley' is that creepy feeling you get when an AI face is almost human, but something is just... off.",
        "AI image generators don't 'think'. They're like super-powered autocomplete for pictures, trained on billions of images from the internet.",
        "Some video game developers now use AI to help create realistic landscapes and characters, saving months of work.",
        "Ever seen a meme that's just a little too weird? It might have been born from an AI meme generator.",
        "AI can now create 'deepfake' videos that are so convincing, they can put words in a politician's mouth or place an actor in a movie they never starred in.",
        "The first AI-generated artwork sold at auction for over $400,000. The art world is still arguing about it.",
        "AI image generation is a 'diffusion' process. The AI starts with digital 'noise' (like TV static) and slowly shapes it into a picture, like a sculptor carving marble.",
        "AI struggles with hands and text for the same reason: they're incredibly complex and have very specific rules that are hard to learn from just looking at pictures.",
        "Some AI models are trained on so much data that they start to learn about the world in surprising ways, like associating certain colors with emotions.",
        "You can 'outpaint' with AI, extending a famous painting like the Mona Lisa to see what might have been just outside the frame.",
        "AI-generated 'people' are being used as virtual influencers on Instagram, with hundreds of thousands of followers.",
        "There are AI tools that can turn your rough sketches into photorealistic images.",
        "AI-generated music is a thing. There are entire albums created by AI, from classical to death metal.",
        "The same text prompt given to an AI image generator will create a different image every single time. It's like rolling a dice with infinite sides.",
        "AI can be used to restore old photos and videos, bringing historical figures to life in stunning detail.",
        "Some sci-fi movie posters from the 70s and 80s look eerily similar to modern AI art, with their surreal and dreamlike imagery.",
        "AI-generated 'art' has won art competitions, causing a huge uproar among human artists.",
        "In the future, video games could have AI-generated missions and stories that are unique to every player.",
        "There are websites that let you create your own AI-generated images just by typing in a few words. The future is now.",
        "AI is getting so good at creating images that there are now AI models that are trained to detect other AI-generated images.",
        "The term 'deepfake' comes from 'deep learning' (the AI technology) and 'fake'.",
        "AI-generated images can have hidden 'watermarks' that are invisible to the human eye but can be detected by a computer.",
        "Some of the most popular AI image generators have names that sound like they're from a sci-fi novel, like 'Midjourney' and 'DALL-E'.",
        "By playing this game, you're not just having fun - you're training your brain to be a more critical consumer of online content. Go you!"
      ]
    };
  }

  /**
   * Get embedded inspirational content (replaces file reading)
   */
  private getEmbeddedInspiration(): { quotes: string[]; jokes: string[] } {
    return {
      quotes: [
        "Every expert was once a beginner. Keep practicing your AI detection skills!",
        "Your human intuition is valuable in our increasingly digital world.",
        "Practice makes perfect - each game makes you better at spotting AI content.",
        "Trust your instincts - humans have evolved to notice when something feels 'off'.",
        "The future belongs to those who can work alongside AI while maintaining their human judgment.",
        "Every mistake is a learning opportunity to sharpen your visual perception.",
        "You're developing a superpower for the digital age - the ability to spot artificial content.",
        "Remember: AI is a tool created by humans, and humans can learn to understand it.",
        "Your curiosity and attention to detail are your greatest assets in this challenge.",
        "The more you play, the more you're training your brain to see what others might miss."
      ],
      jokes: [
        "Why don't AI images win at poker? They always have a tell - extra fingers!",
        "What's an AI's favorite type of photography? Anything without hands in the shot!",
        "Why did the AI go to art school? To learn proper finger counting!",
        "What do you call an AI that's bad at generating text? A spell-wreck generator!",
        "Why don't AI artists ever get tired? Because they never have to lift a finger... or count them!",
        "What's the difference between AI art and human art? About 2.7 extra fingers per hand!",
        "Why did the AI image fail the driving test? It couldn't handle the wheel properly!",
        "What's an AI's least favorite game? Rock, paper, scissors... it always generates rock, paper, scissors, thumb, pinky!",
        "Why don't AI models make good comedians? Their timing is always a bit off by a few milliseconds!",
        "What did the AI say when it finally generated perfect hands? 'I've got to hand it to myself!'"
      ]
    };
  }

  /**
   * Validate that loaded content has the expected structure
   */
  private validateContentStructure(tips: any, facts: any, inspiration: any): void {
    if (!tips.tips || !Array.isArray(tips.tips)) {
      throw new Error('Invalid tips structure: expected { tips: string[] }');
    }
    if (!facts.facts || !Array.isArray(facts.facts)) {
      throw new Error('Invalid facts structure: expected { facts: string[] }');
    }
    if (!inspiration.quotes || !Array.isArray(inspiration.quotes) ||
        !inspiration.jokes || !Array.isArray(inspiration.jokes)) {
      throw new Error('Invalid inspiration structure: expected { quotes: string[], jokes: string[] }');
    }
  }

  /**
   * Provide fallback content if files fail to load
   */
  private getFallbackContent(): ContentFiles {
    return {
      tips: {
        tips: [
          "Look for unnatural lighting or shadows that don't match the scene.",
          "Check hands and fingers carefully - AI often generates extra fingers.",
          "Examine text in images - AI-generated text is often blurry or nonsensical."
        ]
      },
      facts: {
        facts: [
          "AI image generators learn by studying millions of real photos.",
          "Modern AI can create images in seconds that would take human artists hours.",
          "AI image generators use neural networks inspired by human brains."
        ]
      },
      inspiration: {
        quotes: [
          "Every expert was once a beginner. Keep practicing!",
          "Your human intuition is valuable in the digital age.",
          "Practice makes perfect - each game makes you better."
        ],
        jokes: [
          "Why don't AI images win at poker? They always have a tell - extra fingers!",
          "What's an AI's favorite photography? Anything without hands!",
          "Why did the AI go to art school? To learn proper finger counting!"
        ]
      }
    };
  }

  /**
   * Get current date in YYYY-MM-DD format
   */
  private getCurrentDate(): string {
    return new Date().toISOString().split('T')[0] || new Date().toISOString().substring(0, 10);
  }

  /**
   * Load and cache content, refreshing daily
   */
  private ensureContentLoaded(): void {
    const currentDate = this.getCurrentDate();
    
    if (!this.contentCache || this.lastLoadDate !== currentDate) {
      const contentFiles = this.loadContentFromFiles();
      
      this.contentCache = {
        tips: contentFiles.tips.tips,
        facts: contentFiles.facts.facts,
        quotes: contentFiles.inspiration.quotes,
        jokes: contentFiles.inspiration.jokes
      };
      
      this.lastLoadDate = currentDate;
      console.log(`Content loaded for date: ${currentDate}`);
    }
  }

  /**
   * Get educational content for the current day
   */
  public getDailyEducationalContent(): EducationalContent {
    this.ensureContentLoaded();
    
    if (!this.contentCache) {
      throw new Error('Failed to load educational content');
    }

    // Use date-based rotation for consistent daily content
    const currentDate = this.getCurrentDate();
    const dateHash = this.hashString(currentDate);
    
    const tipIndex = dateHash % this.contentCache.tips.length;
    const factIndex = (dateHash + 1) % this.contentCache.facts.length;

    return {
      tips: this.contentCache.tips,
      facts: this.contentCache.facts,
      currentTipIndex: tipIndex,
      currentFactIndex: factIndex
    };
  }

  /**
   * Get inspirational content for the current day
   */
  public getDailyInspirationContent(): InspirationContent {
    this.ensureContentLoaded();
    
    if (!this.contentCache) {
      throw new Error('Failed to load inspirational content');
    }

    // Use date-based rotation for consistent daily content
    const currentDate = this.getCurrentDate();
    const dateHash = this.hashString(currentDate);
    
    // Alternate between quotes and jokes based on date
    const useQuotes = dateHash % 2 === 0;
    const contentArray = useQuotes ? this.contentCache.quotes : this.contentCache.jokes;
    const contentIndex = Math.floor(dateHash / 2) % contentArray.length;

    return {
      quotes: this.contentCache.quotes,
      jokes: this.contentCache.jokes,
      currentIndex: contentIndex,
      type: useQuotes ? 'quote' : 'joke'
    };
  }

  /**
   * Simple string hash function for consistent daily rotation
   */
  private hashString(str: string): number {
    let hash = 0;
    for (let i = 0; i < str.length; i++) {
      const char = str.charCodeAt(i);
      hash = ((hash << 5) - hash) + char;
      hash = hash & hash; // Convert to 32-bit integer
    }
    return Math.abs(hash);
  }

  /**
   * Get current tip for display
   */
  public getCurrentTip(): string {
    const content = this.getDailyEducationalContent();
    return content.tips[content.currentTipIndex] || content.tips[0] || 'No tip available';
  }

  /**
   * Get current fact for display
   */
  public getCurrentFact(): string {
    const content = this.getDailyEducationalContent();
    return content.facts[content.currentFactIndex] || content.facts[0] || 'No fact available';
  }

  /**
   * Get current inspirational content for display
   */
  public getCurrentInspiration(): string {
    const content = this.getDailyInspirationContent();
    const contentArray = content.type === 'quote' ? content.quotes : content.jokes;
    return contentArray[content.currentIndex] || contentArray[0] || 'Stay positive!';
  }

  /**
   * Get a random tip for each game session
   */
  public getRandomTip(): string {
    this.ensureContentLoaded();
    
    if (!this.contentCache || this.contentCache.tips.length === 0) {
      return 'Look for unnatural lighting or shadows that don\'t match the scene.';
    }

    const randomIndex = Math.floor(Math.random() * this.contentCache.tips.length);
    return this.contentCache.tips[randomIndex] || 'Look for unnatural lighting or shadows that don\'t match the scene.';
  }

  /**
   * Get a random fact for each game session
   */
  public getRandomFact(): string {
    this.ensureContentLoaded();
    
    if (!this.contentCache || this.contentCache.facts.length === 0) {
      return 'AI image generators learn by studying millions of real photos.';
    }

    const randomIndex = Math.floor(Math.random() * this.contentCache.facts.length);
    return this.contentCache.facts[randomIndex] || 'AI image generators learn by studying millions of real photos.';
  }

  /**
   * Get random inspirational content for each game session
   */
  public getRandomInspiration(): string {
    this.ensureContentLoaded();
    
    if (!this.contentCache) {
      return 'Stay positive!';
    }

    // Randomly choose between quotes and jokes
    const useQuotes = Math.random() < 0.5;
    const contentArray = useQuotes ? this.contentCache.quotes : this.contentCache.jokes;
    
    if (contentArray.length === 0) {
      return 'Stay positive!';
    }

    const randomIndex = Math.floor(Math.random() * contentArray.length);
    return contentArray[randomIndex] || 'Stay positive!';
  }

  /**
   * Force reload content (useful for testing or manual refresh)
   */
  public forceReload(): void {
    this.contentCache = null;
    this.lastLoadDate = null;
    this.ensureContentLoaded();
  }

  /**
   * Get all available content for API responses
   */
  public getAllContent(): {
    educational: EducationalContent;
    inspirational: InspirationContent;
  } {
    return {
      educational: this.getDailyEducationalContent(),
      inspirational: this.getDailyInspirationContent()
    };
  }
}

export const contentManager = ContentManager.getInstance();
